import Foundation
import SwiftData

/// `DownloadRepository` over SwiftData, the payload store, and a transport.
///
/// One actor owns the queue: its `ModelContext`, the single drain loop, the active
/// download, and every observer. One loop is what makes "exactly one entry
/// downloading" true by construction rather than by coordination.
///
/// A `ModelActor` written out rather than generated by `@ModelActor`, because it
/// holds dependencies beyond the container.
actor DefaultDownloadRepository: DownloadRepository, ModelActor {

    nonisolated let modelExecutor: any ModelExecutor
    nonisolated let modelContainer: ModelContainer

    private let store: ChapterPayloadStore
    private let downloader: ChapterDownloader
    private let now: @Sendable () -> Date

    private var observers = Broadcaster<DownloadQueueSnapshot>()
    private var drainTask: Task<Void, Never>?
    private var active: ActiveDownload?
    private var cachedStorageBytes: Int64?

    private struct ActiveDownload {
        let key: String
        let task: Task<Int64, any Error>
        var progress: DownloadProgress
    }

    init(
        modelContainer: ModelContainer,
        store: ChapterPayloadStore,
        transport: any DownloadTransport,
        now: @escaping @Sendable () -> Date = { .now }
    ) {
        let context = ModelContext(modelContainer)
        context.autosaveEnabled = false
        self.modelExecutor = DefaultSerialModelExecutor(modelContext: context)
        self.modelContainer = modelContainer
        self.store = store
        self.downloader = ChapterDownloader(store: store, transport: transport)
        self.now = now
    }

    // MARK: - Queueing

    func enqueue(
        _ chapters: [Chapter], seriesTitle: String, contentType: ContentType
    ) throws -> Int {
        var sequence = try highestSequence() + 1
        var queued = 0
        var seen: Set<String> = []

        for chapter in chapters {
            let key = EntityKey.identity(sourceID: chapter.sourceID, url: chapter.url)
            guard seen.insert(key).inserted else { continue }

            if let existing = try entity(key) {
                // Queued or stored: nothing to do. Failed: back of the queue.
                guard existing.stateRaw == DownloadStateRaw.failed.rawValue else { continue }
                existing.stateRaw = DownloadStateRaw.pending.rawValue
                existing.errorMessage = nil
                existing.sequence = sequence
            } else {
                modelContext.insert(
                    DownloadEntity(
                        sourceID: chapter.sourceID,
                        seriesURL: chapter.seriesURL.absoluteString,
                        chapterURL: chapter.url.absoluteString,
                        chapterName: chapter.name,
                        chapterNumber: chapter.number,
                        seriesTitle: seriesTitle,
                        contentTypeRaw: contentType.rawValue,
                        enqueuedAt: now(),
                        sequence: sequence))
            }
            sequence += 1
            queued += 1
        }

        guard queued > 0 else { return 0 }
        try saveOrRollBack()
        publish()
        startDraining()
        return queued
    }

    func retry(_ chapter: ChapterID) throws {
        guard let existing = try entity(key(chapter)),
            existing.stateRaw == DownloadStateRaw.failed.rawValue
        else { return }
        existing.stateRaw = DownloadStateRaw.pending.rawValue
        existing.errorMessage = nil
        existing.sequence = try highestSequence() + 1
        try saveOrRollBack()
        publish()
        startDraining()
    }

    func cancel(_ chapter: ChapterID) throws {
        let key = key(chapter)
        guard let existing = try entity(key),
            existing.stateRaw != DownloadStateRaw.completed.rawValue,
            let seriesURL = URL(string: existing.seriesURL)
        else { return }

        // Deleted before the fetch is cancelled, so the fetch's completion finds
        // no entry and cleans up rather than recording a failure.
        modelContext.delete(existing)
        try saveOrRollBack()
        if active?.key == key {
            active?.task.cancel()
        }
        store.discardPartial(for: chapter, seriesURL: seriesURL)
        publish()
    }

    // MARK: - Reading

    func storedContent(for chapter: ChapterID) -> ChapterContent? {
        guard let existing = try? entity(key(chapter)),
            existing.stateRaw == DownloadStateRaw.completed.rawValue,
            let seriesURL = URL(string: existing.seriesURL)
        else { return nil }

        if let content = store.content(for: chapter, seriesURL: seriesURL) {
            return content
        }
        // Recorded as stored, but the payload is gone or incomplete — removed by
        // hand, or by the system restoring a backup without it. It must not keep
        // claiming to be downloaded.
        existing.stateRaw = DownloadStateRaw.failed.rawValue
        existing.errorMessage = "The downloaded files are missing. Download it again."
        existing.isRetryable = true
        existing.byteCount = 0
        try? saveOrRollBack()
        cachedStorageBytes = nil
        publish()
        return nil
    }

    func snapshot() throws -> DownloadQueueSnapshot {
        currentSnapshot()
    }

    func updates() -> AsyncStream<DownloadQueueSnapshot> {
        let (stream, continuation) = AsyncStream.makeStream(
            of: DownloadQueueSnapshot.self, bufferingPolicy: .bufferingNewest(1))
        let id = observers.add(continuation)
        continuation.yield(currentSnapshot())
        continuation.onTermination = { [weak self] _ in
            Task { await self?.removeObserver(id) }
        }
        return stream
    }

    // MARK: - Draining

    func resume() {
        // An entry still marked downloading was interrupted by the app ending; it
        // goes back to pending rather than being left stuck (`download-enqueue`).
        let downloading = DownloadStateRaw.downloading.rawValue
        let interrupted =
            (try? modelContext.fetch(
                FetchDescriptor<DownloadEntity>(
                    predicate: #Predicate { $0.stateRaw == downloading })
            )) ?? []
        if active == nil {
            for entry in interrupted {
                entry.stateRaw = DownloadStateRaw.pending.rawValue
            }
            if !interrupted.isEmpty {
                try? saveOrRollBack()
                publish()
            }
        }
        startDraining()
    }

    func drainUntilIdle() async {
        resume()
        let drain = drainTask
        await withTaskCancellationHandler {
            await drain?.value
        } onCancel: {
            Task { await self.stopDraining() }
        }
    }

    /// Waits for the drain loop to go idle. For tests.
    func waitUntilIdle() async {
        await drainTask?.value
    }

    private func stopDraining() {
        drainTask?.cancel()
        active?.task.cancel()
    }

    private func startDraining() {
        guard drainTask == nil else { return }
        drainTask = Task { await drainLoop() }
    }

    private func drainLoop() async {
        while !Task.isCancelled, let job = nextJob() {
            await download(job)
        }
        // No suspension between the last `nextJob()` and this, so an enqueue
        // cannot slip in between and be stranded.
        drainTask = nil
    }

    private func nextJob() -> DownloadJob? {
        let pending = DownloadStateRaw.pending.rawValue
        var descriptor = FetchDescriptor<DownloadEntity>(
            predicate: #Predicate { $0.stateRaw == pending },
            sortBy: [SortDescriptor(\.sequence)])
        descriptor.fetchLimit = 1
        guard let entity = try? modelContext.fetch(descriptor).first,
            let entry = DownloadMapper.toDomain(entity, progress: nil)
        else { return nil }
        return DownloadJob(key: entity.key, chapter: entry.chapter, contentType: entry.contentType)
    }

    private func download(_ job: DownloadJob) async {
        guard let entity = try? entity(job.key) else { return }
        entity.stateRaw = DownloadStateRaw.downloading.rawValue
        try? saveOrRollBack()

        // Detached: the fetch and its file writes run off this actor, so the queue
        // stays responsive to cancel and enqueue while a chapter downloads. It
        // holds the repository only until this chapter finishes.
        let downloader = self.downloader
        let repository = self
        let task = Task.detached {
            try await downloader.download(job) { progress in
                await repository.report(progress, for: job.key)
            }
        }
        active = ActiveDownload(key: job.key, task: task, progress: .indeterminate)
        publish()

        let outcome = await task.result
        active = nil
        finish(job, outcome: outcome)
    }

    private func finish(_ job: DownloadJob, outcome: Result<Int64, any Error>) {
        let seriesURL = job.chapter.seriesURL
        guard let entity = try? entity(job.key) else {
            // Cancelled or deleted while it ran: whatever it wrote goes too.
            store.delete(job.chapter.id, seriesURL: seriesURL)
            cachedStorageBytes = nil
            publish()
            return
        }

        switch outcome {
        case .success(let bytes):
            entity.stateRaw = DownloadStateRaw.completed.rawValue
            entity.byteCount = bytes
            entity.errorMessage = nil
        case .failure(let error) where error is CancellationError:
            // Stopped, not failed — the processing task's time ran out. Resumes.
            store.discardPartial(for: job.chapter.id, seriesURL: seriesURL)
            entity.stateRaw = DownloadStateRaw.pending.rawValue
        case .failure(let error):
            store.discardPartial(for: job.chapter.id, seriesURL: seriesURL)
            entity.stateRaw = DownloadStateRaw.failed.rawValue
            entity.errorMessage = error.localizedDescription
            entity.isRetryable = (error as? SourceError)?.isRetryable ?? true
        }
        try? saveOrRollBack()
        cachedStorageBytes = nil
        publish()
    }

    private func report(_ progress: DownloadProgress, for key: String) {
        guard active?.key == key else { return }
        active?.progress = progress
        publish()
    }

    // MARK: - Publishing

    private func publish() {
        guard !observers.isEmpty else { return }
        observers.send(currentSnapshot())
    }

    private func currentSnapshot() -> DownloadQueueSnapshot {
        let entities =
            (try? modelContext.fetch(
                FetchDescriptor<DownloadEntity>(sortBy: [SortDescriptor(\.sequence)]))) ?? []
        let entries = entities.compactMap { entity in
            DownloadMapper.toDomain(
                entity, progress: entity.key == active?.key ? active?.progress : nil)
        }
        return DownloadQueueSnapshot(entries: entries, storageBytes: storageBytes())
    }

    /// Recomputed from disk after anything that changes it, never maintained by
    /// arithmetic that could drift from what is really there.
    private func storageBytes() -> Int64 {
        if let cachedStorageBytes { return cachedStorageBytes }
        let bytes = store.totalSize()
        cachedStorageBytes = bytes
        return bytes
    }

    private func removeObserver(_ id: UUID) {
        observers.remove(id)
    }

}

// Deletion and store access, kept apart from the queue's lifecycle above.
extension DefaultDownloadRepository {

    // MARK: - Deleting

    func delete(_ chapters: [ChapterID]) throws {
        for chapter in chapters {
            let key = key(chapter)
            guard let existing = try entity(key), let seriesURL = URL(string: existing.seriesURL)
            else { continue }
            if active?.key == key {
                active?.task.cancel()
            }
            modelContext.delete(existing)
            store.delete(chapter, seriesURL: seriesURL)
        }
        try saveOrRollBack()
        cachedStorageBytes = nil
        publish()
    }

    func deleteAll(in series: SeriesID) throws {
        let sourceID = series.sourceID
        let seriesURL = series.url.absoluteString
        let entries = try modelContext.fetch(
            FetchDescriptor<DownloadEntity>(
                predicate: #Predicate { $0.sourceID == sourceID && $0.seriesURL == seriesURL }))
        for entry in entries {
            if active?.key == entry.key {
                active?.task.cancel()
            }
            modelContext.delete(entry)
        }
        try saveOrRollBack()
        store.deleteSeries(sourceID: series.sourceID, seriesURL: series.url)
        cachedStorageBytes = nil
        publish()
    }

    func deleteAll() throws {
        active?.task.cancel()
        try modelContext.delete(model: DownloadEntity.self)
        try saveOrRollBack()
        store.deleteAll()
        cachedStorageBytes = nil
        publish()
    }

    // MARK: - Store helpers

    private func key(_ chapter: ChapterID) -> String {
        EntityKey.identity(sourceID: chapter.sourceID, url: chapter.url)
    }

    private func entity(_ key: String) throws -> DownloadEntity? {
        var descriptor = FetchDescriptor<DownloadEntity>(predicate: #Predicate { $0.key == key })
        descriptor.fetchLimit = 1
        return try modelContext.fetch(descriptor).first
    }

    private func highestSequence() throws -> Int64 {
        var descriptor = FetchDescriptor<DownloadEntity>(
            sortBy: [SortDescriptor(\.sequence, order: .reverse)])
        descriptor.fetchLimit = 1
        return try modelContext.fetch(descriptor).first?.sequence ?? 0
    }

    private func saveOrRollBack() throws {
        do {
            try modelContext.save()
        } catch {
            modelContext.rollback()
            throw error
        }
    }
}
